language: python
python:
 - "3.8"


services:
  - docker

before_script: pip install docker-compose

# Everytime I push a change to github run this test with the lint tool flake8
script: 
  - docker-compose run app sh -c "python manage.py test && flake8"